In [19]:
import numpy as np

# Завдання 1 Створіть одномірний масив (вектор) зі значеннями квадратних коренів з кожного натурального числа, починаючи з 1, та виведіть його значення.
vector_1 = np.sqrt(np.arange(1, 11))  # Квадратні корені натуральних чисел від 1 до 10
print("Завдання 1: вектор квадратних коренів натуральних чисел від 1 до 10")
print(vector_1)


Завдання 1: вектор квадратних коренів натуральних чисел від 1 до 10
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [20]:
# Завдання 2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями коренів 4 ступеня перших дійсних чисел.
matrix_2 = np.power(np.arange(1, 10).reshape(3, 3), 1/4)  # Корені 4 ступеня перших дійсних чисел
print("\nЗавдання 2: матриця 3x3 зі значеннями коренів 4 ступеня перших дійсних чисел")
print(matrix_2)



Завдання 2: матриця 3x3 зі значеннями коренів 4 ступеня перших дійсних чисел
[[1.         1.18920712 1.31607401]
 [1.41421356 1.49534878 1.56508458]
 [1.62657656 1.68179283 1.73205081]]


In [21]:
# Завдання 3 Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від 1 до 50 та знайдіть суму елементів кожного рядка.
array_3 = np.random.randint(1, 51, (3, 3))  # Випадкові натуральні числа від 1 до 50
суми_рядків = array_3.sum(axis=1)
print("\nЗавдання 3: array 3x3 з випадковими натуральними числами від 1 до 50")
print(array_3)
print("суми елементів кожного рядка:", суми_рядків)



Завдання 3: array 3x3 з випадковими натуральними числами від 1 до 50
[[37 24 42]
 [49 47 44]
 [49 40 11]]
суми елементів кожного рядка: [103 140 100]


In [22]:
# Завдання 4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами від -0.9 до 0.9 та виведіть його значення.
array_4 = np.random.uniform(-0.9, 0.9, (4, 4))  # Випадкові дійсні числа від -0.9 до 0.9
print("\nЗавдання 4: масив 4x4 з випадковими дійсними числами від -0.9 до 0.9")
print(array_4)



Завдання 4: масив 4x4 з випадковими дійсними числами від -0.9 до 0.9
[[-0.46469197  0.79353843  0.14676064  0.16944291]
 [-0.86752663 -0.17962692 -0.61121728  0.1582769 ]
 [-0.89211464  0.21576912 -0.05101163  0.17783164]
 [-0.34784095  0.44793993 -0.75547957 -0.64587751]]


In [23]:
# Завдання 5 Створіть два одномірні масиви розміром 7, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та виконайте на них поелементні операції додавання, віднімання та множення.
array_5_1 = np.random.randint(1, 6, 7)  # Перший array
array_5_2 = np.random.randint(1, 6, 7)  # Другий array

додавання = array_5_1 + array_5_2
віднімання = array_5_1 - array_5_2
множення = array_5_1 * array_5_2

print("\nЗавдання 5: Операції над arrayами")
print("Перший масив:", array_5_1)
print("Другий масив:", array_5_2)
print("Додавання:", додавання)
print("Віднімання:", віднімання)
print("Множення:", множення)



Завдання 5: Операції над arrayами
Перший масив: [4 1 2 4 1 1 5]
Другий масив: [4 2 2 3 2 5 1]
Додавання: [8 3 4 7 3 6 6]
Віднімання: [ 0 -1  0  1 -1 -4  4]
Множення: [16  2  4 12  2  5  5]


In [24]:
# Завдання 6 Створіть дві матриці розміром 3x3, заповніть їх довільними цілими числами від 0 до 5 та знайдіть їх добуток.
matrix_6_1 = np.random.randint(0, 6, (3, 3))  # Перша matrix
matrix_6_2 = np.random.randint(0, 6, (3, 3))  # Друга matrix

добуток_6 = np.dot(matrix_6_1, matrix_6_2)

print("\nЗавдання 6: Добуток двох матриць 3x3")
print("Перша матриця:")
print(matrix_6_1)
print("Друга матриця:")
print(matrix_6_2)
print("Добуток:")
print(добуток_6)



Завдання 6: Добуток двох матриць 3x3
Перша матриця:
[[0 2 2]
 [4 2 5]
 [2 4 1]]
Друга матриця:
[[5 4 5]
 [2 2 5]
 [1 5 5]]
Добуток:
[[ 6 14 20]
 [29 45 55]
 [19 21 35]]


In [25]:
# Завдання 7 Створіть дві матриці розміром 2x3 та 3x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 7 та перемножте їх між собою.
matrix_7_1 = np.random.randint(1, 8, (2, 3))  # Перша matrix 2x3
matrix_7_2 = np.random.randint(1, 8, (3, 4))  # Друга matrix 3x4

добуток_7 = np.dot(matrix_7_1, matrix_7_2)

print("\nЗавдання 7: Добуток матриць 2x3 та 3x4")
print("Перша матриця:")
print(matrix_7_1)
print("Друга матриця:")
print(matrix_7_2)
print("Добуток:")
print(добуток_7)



Завдання 7: Добуток матриць 2x3 та 3x4
Перша матриця:
[[7 6 1]
 [1 4 1]]
Друга матриця:
[[5 5 4 3]
 [6 3 6 2]
 [3 2 2 3]]
Добуток:
[[74 55 66 36]
 [32 19 30 14]]


In [26]:
# Завдання 8 Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 15 та знайдіть її обернену матрицю.

matrix_8 = np.random.randint(1, 16, (2, 2))  # matrix 2x2

inverse_matrix_8 = np.linalg.inv(matrix_8)

print("\nЗавдання 8: Обернена матриця 2x2")
print("matrix:")
print(matrix_8)
print("Обернена матриця:")
print(inverse_matrix_8)



Завдання 8: Обернена матриця 2x2
matrix:
[[11 12]
 [12 15]]
Обернена матриця:
[[ 0.71428571 -0.57142857]
 [-0.57142857  0.52380952]]


In [27]:
# Завдання 9 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 3 до 15 та транспонуйте її.
matrix_9 = np.random.randint(3, 16, (3, 3))  # matrix 3x3


transposed_matrix_9 = np.transpose(matrix_9)

print("\nЗавдання 9: Транспонована матриця 3x3")
print("матриця:")
print(matrix_9)
print("Транспонована матриця:")
print(transposed_matrix_9)



Завдання 9: Транспонована матриця 3x3
матриця:
[[12 11 14]
 [11  5 10]
 [ 9 13 10]]
Транспонована матриця:
[[12 11  9]
 [11  5 13]
 [14 10 10]]


In [28]:
# Завдання 10 Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.
matrix_10 = np.random.randint(1, 11, (3, 4))  # matrix 3x4
vector_10 = np.random.randint(1, 11, (4, 1))  # vector 4x1

добуток_10 = np.dot(matrix_10, vector_10)

print("\nЗавдання 10: Добуток матриці 3x4 на вектор 4x1")
print("матриця:")
print(matrix_10)
print("вектор:")
print(vector_10)
print("Добуток:")
print(добуток_10)



Завдання 10: Добуток матриці 3x4 на вектор 4x1
матриця:
[[10  8  9  7]
 [ 9  6  9 10]
 [ 7  1  9  9]]
вектор:
[[5]
 [1]
 [6]
 [5]]
Добуток:
[[147]
 [155]
 [135]]


In [29]:
# Завдання 11 Створіть дві матриці розміром 2x3 та 3x3, заповніть першу матрицю випадковими цілими числами в діапазоні від 1 до 5, а другу - випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть добуток двох елементів першої матриці.
matrix_11_1 = np.random.randint(1, 6, (2, 3))  # matrix 2x3
matrix_11_2 = np.random.uniform(-1, 1, (3, 3))  # matrix 3x3

добуток_елементів_11 = matrix_11_1[0, 0] * matrix_11_1[1, 1]

print("\nЗавдання 11: Добуток двох елементів першої матриці 2x3")
print("Перша матриця:")
print(matrix_11_1)
print("Друга матриця:")
print(matrix_11_2)
print("Добуток елементів:", добуток_елементів_11)



Завдання 11: Добуток двох елементів першої матриці 2x3
Перша матриця:
[[4 5 2]
 [4 3 4]]
Друга матриця:
[[-0.50410505 -0.21329814 -0.90634496]
 [-0.7670431  -0.35308359  0.00857962]
 [-0.70073293  0.39938966 -0.29455283]]
Добуток елементів: 12


In [30]:
# Завдання 12 Створіть матрицю розміром 3x4 та заповніть її випадковими дійсними числами в діапазоні від -0.9 до 0.9 та обчисліть її визначник.
matrix_12 = np.random.uniform(-0.9, 0.9, (3, 4))  # matrix 3x4

# Визначник можна обчислити лише для квадратної матриці, тому тут ми будемо обчислювати псевдо-визначник (через SVD)
U, S, Vt = np.linalg.svd(matrix_12)
псевдо_визначник_12 = np.prod(S)

print("\nЗавдання 12: Псевдо-визначник матриці 3x4")
print("matrix:")
print(matrix_12)
print("Псевдо-визначник:", псевдо_визначник_12)



Завдання 12: Псевдо-визначник матриці 3x4
matrix:
[[-0.37872204  0.70927283  0.5324649  -0.12869096]
 [ 0.70330759  0.37550893 -0.64258167  0.28008072]
 [ 0.52380449  0.58895543 -0.50057744  0.25890005]]
Псевдо-визначник: 0.06194645922859759


In [31]:
# Завдання 13 Створіть масив розміром 2x3 та вектор розміром 3x1, заповніть масив випадковими цілими числами в діапазоні від 1 до 5, а вектор - випадковими дійсними числами в діапазоні від -1 до 1, та знайдіть їх добуток.
array_13 = np.random.randint(1, 6, (2, 3))  # array 2x3
vector_13 = np.random.uniform(-1, 1, (3, 1))  # vector 3x1

добуток_13 = np.dot(array_13, vector_13)

print("\nЗавдання 13: Добуток масиву 2x3 на вектор 3x1")
print("array:")
print(array_13)
print("vector:")
print(vector_13)
print("Добуток:")
print(добуток_13)



Завдання 13: Добуток масиву 2x3 на вектор 3x1
array:
[[2 3 4]
 [2 1 5]]
vector:
[[-0.69125823]
 [ 0.85790767]
 [ 0.98185685]]
Добуток:
[[5.11863391]
 [4.38467543]]


In [32]:
# Завдання 14 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток її головної діагоналі.
matrix_14 = np.random.randint(1, 11, (3, 3))  # matrix 3x3

добуток_діагоналі_14 = np.prod(np.diag(matrix_14))

print("\nЗавдання 14: Добуток головної діагоналі матриці 3x3")
print("matrix:")
print(matrix_14)
print("Добуток головної діагоналі:", добуток_діагоналі_14)



Завдання 14: Добуток головної діагоналі матриці 3x3
matrix:
[[ 9 10  4]
 [ 2  4  9]
 [ 7  7 10]]
Добуток головної діагоналі: 360


In [34]:
# Завдання 15 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 5 та знайдіть вектор-стовпчик, що містить суму елементів кожного стовпця матриці.
matrix_15 = np.random.randint(1, 6, (3, 3))  # matrix 3x3

vector_sum_15 = matrix_15.sum(axis=0).reshape(-1, 1)

print("\nЗавдання 15: вектор-стовпчик сум елементів кожного стовпця матриці 3x3")
print("matrix:")
print(matrix_15)
print("вектор-стовпчик сум елементів кожного стовпця:")
print(vector_sum_15)



Завдання 15: вектор-стовпчик сум елементів кожного стовпця матриці 3x3
matrix:
[[2 3 5]
 [1 2 4]
 [1 4 2]]
вектор-стовпчик сум елементів кожного стовпця:
[[ 4]
 [ 9]
 [11]]


In [ ]:
#Висновок: Ці 15 завдань демонструють основні операції з масивами та матрицями за допомогою бібліотеки NumPy в Python. Вони допомагають зрозуміти, як ефективно використовувати NumPy для обробки числових даних, виконання складних математичних операцій, а також роботи з великими наборами даних. Виконання таких завдань дозволяє підвищити рівень навичок роботи з Python та закріпити розуміння основ лінійної алгебри в програмуванні.